sudo: required
language: c # Choose a minimal base image.

script:
  - sudo ./build-nix.sh

cache:
  directories:
    - downloads

after_success:
  # List output to confirm reproducibilty.
  - sha256sum out/*

notifications:
  email: false
